// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.1";

// src/lib/mcp/tools/list-my-bills.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z } from "npm:zod@3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.86.2";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((value) => typeof value === "string" && value.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("A Supabase publishable key is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("Authenticated AJMS user required");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-my-bills.ts
var list_my_bills_default = defineTool({
  name: "list_my_bills",
  title: "Daftar tagihan saya",
  description: "Menampilkan tagihan AJMS yang dapat diakses oleh pengguna yang sedang masuk.",
  inputSchema: {
    status: z.enum(["all", "unpaid", "partial", "paid"]).default("all").describe("Status pembayaran yang dicari."),
    limit: z.number().int().min(1).max(100).default(20).describe("Jumlah maksimal tagihan.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Silakan masuk dengan akun AJMS." }], isError: true };
    }
    let query = supabaseForUser(ctx).from("bills").select("id,unit_number,quarter_label,bill_type,total_amount,due_date,payment_status,paid_amount,paid_at,notes").order("created_at", { ascending: false }).limit(limit);
    if (status !== "all") query = query.eq("payment_status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: `Gagal membaca tagihan: ${error.message}` }], isError: true };
    const bills = (data ?? []).map((bill) => ({
      id: bill.id,
      unit_number: bill.unit_number,
      period: bill.quarter_label,
      type: bill.bill_type,
      total_amount: bill.total_amount,
      due_date: bill.due_date,
      payment_status: bill.payment_status,
      paid_amount: bill.paid_amount,
      paid_at: bill.paid_at,
      notes: bill.notes
    }));
    return {
      content: [{ type: "text", text: bills.length ? `Ditemukan ${bills.length} tagihan.` : "Tidak ada tagihan yang ditemukan." }],
      structuredContent: { bills }
    };
  }
});

// src/lib/mcp/tools/search-data-token.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z2 } from "npm:zod@3.25.76";
var search_data_token_default = defineTool2({
  name: "search_data_token",
  title: "Cari data token listrik",
  description: "Mencari status dan catatan token listrik unit yang dapat diakses pengguna AJMS.",
  inputSchema: {
    unit_number: z2.string().trim().min(1).max(20).describe("Nomor unit, misalnya A0202 atau KOA1.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ unit_number }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Silakan masuk dengan akun AJMS." }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("data_tokens").select("unit_number,tower,floor,kwh_id,sisa_kwh,tanggal_bypass,tanggal_normalisasi,status,catatan,no_wa,atas_nama,updated_at").ilike("unit_number", unit_number).limit(20);
    if (error) return { content: [{ type: "text", text: `Gagal membaca data token: ${error.message}` }], isError: true };
    const tokens = (data ?? []).map((token) => ({
      unit_number: token.unit_number,
      tower: token.tower,
      floor: token.floor,
      kwh_id: token.kwh_id,
      remaining_kwh: token.sisa_kwh,
      bypass_date: token.tanggal_bypass,
      normalization_date: token.tanggal_normalisasi,
      status: token.status,
      notes: token.catatan,
      whatsapp: token.no_wa,
      account_name: token.atas_nama,
      updated_at: token.updated_at
    }));
    return {
      content: [{ type: "text", text: tokens.length ? `Ditemukan ${tokens.length} data token.` : "Data token unit tidak ditemukan." }],
      structuredContent: { tokens }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "yeehwobmpknqagcolkbo";
var mcp_default = defineMcp({
  name: "andrea-jarrdin-management-system",
  title: "Andrea Jarrdin Management System",
  version: "0.1.0",
  instructions: "Gunakan alat AJMS untuk membaca tagihan pengguna dan mencari data token listrik sesuai hak akses akun yang terhubung.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_my_bills_default, search_data_token_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
